backend:
  name: github
  repo: mohekouzhuxiangyu/blog
  branch: main
  base_url: https://oauth.decapcms.org
  auth_endpoint: auth

publish_mode: editorial_workflow

media_folder: public/images
public_folder: /blog/images

collections:
  - name: posts
    label: "Posts"
    folder: content
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
